/*
 * This file is generated by ITEnumerator.java.template
 */
 
package c41.utility.linq.enumerator;

/**
 * 基本类型byte的Enumerator。
 */
public interface IByteEnumerator extends IEnumerator<Byte>{

	@Override
	public default Byte next() {
		moveNext();
		return current();
	}
	
	public default byte nextByte() {
		moveNext();
		return currentByte();
	}
	
	@Override
	public default Byte current() {
		return currentByte();
	}
	
	public byte currentByte();
	
}
