/*
 * This file is generated by ITEnumerator.java.template
 */
 
package c41.utility.linq.enumerator;

/**
 * 基本类型double的Enumerator。
 */
public interface IDoubleEnumerator extends IEnumerator<Double>{

	@Override
	public default Double next() {
		moveNext();
		return current();
	}
	
	public default double nextDouble() {
		moveNext();
		return currentDouble();
	}
	
	@Override
	public default Double current() {
		return currentDouble();
	}
	
	public double currentDouble();
	
}
