/*
 * This file is generated by ITEnumerator.java.template
 */
 
package c41.utility.linq.enumerator;

/**
 * 基本类型float的Enumerator。
 */
public interface IFloatEnumerator extends IEnumerator<Float>{

	@Override
	public default Float next() {
		moveNext();
		return current();
	}
	
	public default float nextFloat() {
		moveNext();
		return currentFloat();
	}
	
	@Override
	public default Float current() {
		return currentFloat();
	}
	
	public float currentFloat();
	
}
