/*
 * This file is generated by IForeachTAction.java.template
 */

package c41.lambda.action;

@FunctionalInterface
public interface IForeachByteAction extends IForeachAction<Byte>{

	public void invoke(byte ch, int i);
	
	@Override
	public default void invoke(Byte ch, int i) {
		invoke((byte)ch, i);
	}
	
}
