/*
 * This file is generated by IForeachTAction.java.template
 */

package c41.lambda.action;

@FunctionalInterface
public interface IForeachFloatAction extends IForeachAction<Float>{

	public void invoke(float ch, int i);
	
	@Override
	public default void invoke(Float ch, int i) {
		invoke((float)ch, i);
	}
	
}
