/*
 * This file is generated by ITAction.java.template
 */

package c41.lambda.action;

@FunctionalInterface
public interface IIntAction extends IAction1<Integer>{

	public void invoke(int val);
	
	@Override
	public default void invoke(Integer val) {
		invoke((int)val);
	}
	
}
