/*
 * This file is generated by ITAction.java.template
 */

package c41.lambda.action;

@FunctionalInterface
public interface ILongAction extends IAction1<Long>{

	public void invoke(long val);
	
	@Override
	public default void invoke(Long val) {
		invoke((long)val);
	}
	
}
