/*
 * This file is generated by ITAction.java.template
 */

package c41.lambda.action;

@FunctionalInterface
public interface IShortAction extends IAction1<Short>{

	public void invoke(short val);
	
	@Override
	public default void invoke(Short val) {
		invoke((short)val);
	}
	
}
