/*
 * This file is generated by ITEnumerator.java.template
 */
 
package c41.utility.linq.enumerator;

/**
 * 基本类型byte的Enumerator。
 */
public interface IByteEnumerator extends IEnumerator<Byte>{

	@Override
	public default Byte next() {
		return nextByte();
	}
	
	public byte nextByte();
	
}
