/*
 * This file is generated by ITEnumerator.java.template
 */
 
package c41.utility.linq.enumerator;

/**
 * 基本类型char的Enumerator。
 */
public interface ICharEnumerator extends IEnumerator<Character>{

	@Override
	public default Character next() {
		return nextChar();
	}
	
	public char nextChar();
	
}
