/*
 * This file is generated by ITEnumerator.java.template
 */
 
package c41.utility.linq.enumerator;

/**
 * 基本类型double的Enumerator。
 */
public interface IDoubleEnumerator extends IEnumerator<Double>{

	@Override
	public default Double next() {
		return nextDouble();
	}
	
	public double nextDouble();
	
}
