/*
 * This file is generated by ITEnumerator.java.template
 */
 
package c41.utility.linq.enumerator;

/**
 * 基本类型float的Enumerator。
 */
public interface IFloatEnumerator extends IEnumerator<Float>{

	@Override
	public default Float next() {
		return nextFloat();
	}
	
	public float nextFloat();
	
}
