/*
 * This file is generated by ITEnumerator.java.template
 */
 
package c41.utility.linq.enumerator;

/**
 * 基本类型long的Enumerator。
 */
public interface ILongEnumerator extends IEnumerator<Long>{

	@Override
	public default Long next() {
		return nextLong();
	}
	
	public long nextLong();
	
}
