/*
 * This file is generated by TReference.java.template
 */
 
package c41.core.reference;

public class ByteReference {

	public byte value;
	
	public ByteReference() {}
	
	public ByteReference(byte value) {this.value = value;}
	
}
