/*
 * This file is generated by TReference.java.template
 */
 
package c41.core.reference;

public class DoubleReference {

	public double value;
	
	public DoubleReference() {}
	
	public DoubleReference(double value) {this.value = value;}
	
}
