/*
 * This file is generated by TReference.java.template
 */
 
package c41.core.reference;

public class FloatReference {

	public float value;
	
	public FloatReference() {}
	
	public FloatReference(float value) {this.value = value;}
	
}
