/*
 * This file is generated by TReference.java.template
 */
 
package c41.core.reference;

public class IntReference {

	public int value;
	
	public IntReference() {}
	
	public IntReference(int value) {this.value = value;}
	
}
