/*
 * This file is generated by TReference.java.template
 */
 
package c41.core.reference;

public class LongReference {

	public long value;
	
	public LongReference() {}
	
	public LongReference(long value) {this.value = value;}
	
}
