/*
 * This file is generated by TReference.java.template
 */
 
package c41.core.reference;

public class ShortReference {

	public short value;
	
	public ShortReference() {}
	
	public ShortReference(short value) {this.value = value;}
	
}
