/*
 * This file is generated by ITAction.java.template
 */

package c41.lambda.action;

@FunctionalInterface
public interface IByteAction extends IAction1<Byte>{

	public void invoke(byte val);
	
	@Override
	public default void invoke(Byte val) {
		invoke((byte)val);
	}
	
}
