/*
 * This file is generated by IForeachTAction.java.template
 */

package c41.lambda.action;

@FunctionalInterface
public interface IForeachIntAction extends IForeachAction<Integer>{

	public void invoke(int ch, int i);
	
	@Override
	public default void invoke(Integer ch, int i) {
		invoke((int)ch, i);
	}
	
}
