/*
 * This file is generated by IForeachTAction.java.template
 */

package c41.lambda.action;

@FunctionalInterface
public interface IForeachCharAction extends IForeachAction<Character>{

	public void invoke(char ch, int i);
	
	@Override
	public default void invoke(Character ch, int i) {
		invoke((char)ch, i);
	}
	
}
