/*
 * This file is generated by TReference.java.template
 */
 
package c41.core.reference;

public class CharReference {

	public char value;
	
	public CharReference() {}
	
	public CharReference(char value) {this.value = value;}
	
}
