/*
 * This file is generated by ITPredicate.java.template
 */

package c41.lambda.predicate;

public interface IBytePredicate extends IPredicate<Byte>{

	public boolean is(byte val);
	
	@Override
	public default boolean is(Byte val) {
		return is((byte)val);
	}
	
}
