/*
 * This file is generated by ITPredicate.java.template
 */

package c41.lambda.predicate;

public interface IDoublePredicate extends IPredicate<Double>{

	public boolean is(double val);
	
	@Override
	public default boolean is(Double val) {
		return is((double)val);
	}
	
}
