/*
 * This file is generated by ITPredicate.java.template
 */

package c41.lambda.predicate;

public interface ILongPredicate extends IPredicate<Long>{

	public boolean is(long val);
	
	@Override
	public default boolean is(Long val) {
		return is((long)val);
	}
	
}
