/*
 * This file is generated by ITPredicate.java.template
 */

package c41.lambda.predicate;

public interface IShortPredicate extends IPredicate<Short>{

	public boolean is(short val);
	
	@Override
	public default boolean is(Short val) {
		return is((short)val);
	}
	
}
